### ISSUE TITLE
10. As an item, I want my estimated next purchase date to be computed at the time my purchase is recorded in the database so the app can learn how often I buy different items.

### ISSUE THREAD

**Issue by llunaplanet** [the-collab-lab/tcl-32-smart-shopping-list#10]
AC:

* When a purchase is recorded, the estimated number of days until the next purchase date should be calculated and recorded in the database

The script `calculateEstimate` from `@the-collab-lab/shopping-list-utils` should be used to calculate the next estimated purchase interval. This should already be installed in your project from [issue 3](https://github.com/the-collab-lab/tcl-33-smart-shopping-list/issues/3)

Notes:

* Think through the data that is needed as inputs to the function in `estimates.js` and how to use the output.
* It is likely at this point you'll need to adjust the schema for an item to accommodate the data points required.

**Comment by JordanRaleigh** [comment]
- [ ] Add fields in DB
    - [ ] # of purchases
    - [ ] Every time user checks purchase box, increment by 1
    - [ ] Next purchase date (output of calculateEstimate)
- [ ] create helper function for logic and use in Item.js

Take in consideration when a user unchecks

**Comment by JordanRaleigh** [comment]
Questions for Office Hours

- [ ] When you change your mind and uncheck, what should the logic be for nextPurchase?

**Comment by JordanRaleigh** [comment]
- [ ] For last purchase date, possibly save in an array in DB instead of in state and when unchecked, bring it back to last entry. 
- [ ] Comment in PR to get further feedback. 
- [ ] Only calculate on first purchase
