### ISSUE TITLE
A user utilizing assistive technology is not able to navigate the page in the proper order

### ISSUE THREAD

**Issue by abowler2** [the-collab-lab/tcl-32-smart-shopping-list#35]
Currently the `NavLinks` render at the bottom of the page, however, they are positioned in the DOM tree at the top. 

Given that screen readers navigate from the top of a page to the bottom this is not an ideal experience for a screen reader user as the link content is announced prior to any of the information on the screen such as the site title.

In addition, there appears to be a missed merge issue that has the `NavLinks` rendering regardless of whether a user has a token or not (and twice if they do have a token, which adds to the confusion for a screen reader user)

By eliminating the extra rendering of the `NavLinks` and moving them to the bottom of the tree (under the Switch statement) the user gets a much improved experience.

### Screen recordings to demonstrate the difference:
<small>(note: I've made a separate comment on the [PR for filtering](https://github.com/the-collab-lab/tcl-32-smart-shopping-list/pull/33#discussion_r744176131) to adjust the structure of the list items)</small>

| current  | adjusted structure |
| ------------- | ------------- |
| <video width=400px src="https://user-images.githubusercontent.com/19564687/140625978-cc44d580-6262-4245-8e44-7d2cd5d3cf0a.mov" /> | <video width=400px src="https://user-images.githubusercontent.com/19564687/140625987-81391b63-7daf-4134-9ca9-c9f36abd8080.mov" />  |

**Comment by JordanRaleigh** [comment]
- [ ] Screenreader skips item name when using tab but reads it when clicking on div section
