### ISSUE TITLE
8. As a user, I want to mark an item on my shopping list as purchased so the app can learn how often I buy different items.

### ISSUE THREAD

**Issue by llunaplanet** [the-collab-lab/tcl-32-smart-shopping-list#8]
AC:

* User is able to tap a checkbox or similar UI element to mark an item in the list as purchased
* Item should be shown as checked for 24 hours after the purchase is made (i.e. we assume the user does not need to buy the item again for at least 1 day)

Notes:

* One challenge your pair may work through is figuring out how they will test this.
* E.g., maybe create a few sample items then go into the Firestore console and manipulate the dates.
* The wirefrrame shows the use of simple checkboxes for this purpose, which is fine for now. https://github.com/the-collab-lab/smart-shopping-list/blob/main/_resources/wireframes/list-populated.png

**Comment by timamero** [comment]
Subtask List:

- [ ] Add checkbox for each item in the list
- [ ] Create `durationSincePurchased` variable with the value of the current date minus the last purchase date
- [ ] When the checkbox is mark, send timestamp to database and update `lastPurchase` field
- [ ] Create function that checks if the value of `durationSincePurchased` is over 24 hours and if it is, uncheck the checkbox
- [ ] In the Add Item form, remove `last purchase date` field; when user submits form, a null value will be saved by default to the `lastPurchase` field.

Edge Cases
* What if user accidently checks something and wants to uncheck it right away?
    * When user unchecks checkbox, set value of `lastPurchase` to null
